### PR TITLE
APP-2222 Dropdown improvements

### PR DESCRIPTION
**Pull request by symphony-annaLlorens**
- Added padding to select small size container
Screenshot 2021-12-24 at 13 38 22

Screenshot 2021-12-24 at 13 40 59

### CODE REVIEW

**Comment by gabrielsetradantas** [comment]
ok to test

**Review by gabrielsetradantas — APPROVED** [review]
LGTM

**Review by AliciaSymphony — DISMISSED** [review]

**Comment by symphony-annaLlorens** [comment]
ok to test

**Review by AliciaSymphony — COMMENTED** [review]
No impact on the Dropdown "single" value?

**Comment by symphony-annaLlorens** [comment]
Screenshot 2021-12-27 at 10 52 16

**Comment by AliciaSymphony** [comment]
> Screenshot 2021-12-27 at 10 52 16

Is the height still 24px ?

**Pull request closed without merging**
